name: My Safe Haven
permalink: :year/:month/:day/:title
baseurl: /diary

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2021
now: 2022
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  #email : yourname@gmail.com
  github : Aspiring-Writer
  #twitter : yourname

# Links in the navigation, you can modify both link name and link url
nav:
  Blog: "/"
  Diary: "/diary"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
# Colors can be changed in `_sass/predefine.scss`